language: csharp
solution: SharpNES.sln
mono: none
dotnet: 3.1.100
script:
  - dotnet restore
  - dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=json,cobertura,lcov,teamcity,opencover
