language: csharp
solution: SharpNES.sln
mono: none
dotnet: 3.1
os: linux
dist: focal

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sdk-3.1

# https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md - 
# The output path for the tests includes a UUID by-design which makes no sense in CI scenarios...
# Oh Microsoft... That's why the `find` step is in there to move the results to a stable location
script:
- dotnet restore
- dotnet tool restore
- dotnet test --results-directory .\TestResults --collect:"XPlat Code Coverage" --settings ./testcoverage.runsettings
- find ./TestResults -mindepth 2 -type f -print -exec mv {} ./TestResults/ \; 
- dotnet tool run csmacnz.Coveralls --opencover -i ./TestResults/coverage.opencover.xml --commitId $TRAVIS_COMMIT --commitMessage "$TRAVIS_COMMIT_MESSAGE" --commitBranch $TRAVIS_BRANCH --jobId $TRAVIS_JOB_ID 
