using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;

namespace SharpNES.Core.CPU.Internal {
  public class MOS6502InstructionLookupTable : IInstructionLookupTable {
    private readonly ICpuInstructionExecutor _executor;
    private readonly IMemoryAddressingModes _addressingModes;
    private readonly ILogger<MOS6502InstructionLookupTable> _logger;

    private readonly List<CpuInstruction> _instructions;

    public MOS6502InstructionLookupTable(
        ICpuInstructionExecutor executor, 
        IMemoryAddressingModes addressingModes, 
        ILogger<MOS6502InstructionLookupTable> logger) {
      _executor = executor ?? throw new ArgumentNullException(nameof(executor));
      _addressingModes = addressingModes ?? throw new ArgumentNullException(nameof(addressingModes));
      _logger = logger ?? throw new ArgumentNullException(nameof(logger));

      _instructions = new List<CpuInstruction>();
      FillInstructionsList();
    }

    public CpuInstruction GetInstructionForOpCode(byte opCode) {
      var opCodeValue = (int)opCode;
      var instruction = _instructions[opCodeValue];
      return instruction;
    }

    private void FillInstructionsList() {
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BRK, MOS6502AddressingMode.Immediate, _executor.BreakInterrupt, _addressingModes.Immediate, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.IndirectX, _executor.OrWithAccumulator, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.ZeroPageZero, _executor.OrWithAccumulator, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ASL, MOS6502AddressingMode.ZeroPageZero, _executor.ArithmeticShiftLeft, _addressingModes.ZeroPageZero, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.PHP, MOS6502AddressingMode.Implicit, _executor.PushProcessorStatus, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.Immediate, _executor.OrWithAccumulator, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ASL, MOS6502AddressingMode.Implicit, _executor.ArithmeticShiftLeft, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.Absolute, _executor.OrWithAccumulator, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ASL, MOS6502AddressingMode.Absolute, _executor.ArithmeticShiftLeft, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BPL, MOS6502AddressingMode.Relative, _executor.BranchOnPlus, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.IndirectY, _executor.OrWithAccumulator, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.ZeroPageX, _executor.OrWithAccumulator, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ASL, MOS6502AddressingMode.ZeroPageX, _executor.ArithmeticShiftLeft, _addressingModes.ZeroPageX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CLC, MOS6502AddressingMode.Implicit, _executor.ClearCarry, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.AbsoluteY, _executor.OrWithAccumulator, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ORA, MOS6502AddressingMode.AbsoluteX, _executor.OrWithAccumulator, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ASL, MOS6502AddressingMode.AbsoluteX, _executor.ArithmeticShiftLeft, _addressingModes.AbsoluteX, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.JSR, MOS6502AddressingMode.Absolute, _executor.JumpSubRoutine, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.IndirectX, _executor.AndWithAccumulator, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BIT, MOS6502AddressingMode.ZeroPageZero, _executor.BitTest, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.ZeroPageZero, _executor.AndWithAccumulator, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROL, MOS6502AddressingMode.ZeroPageZero, _executor.RotateLeft, _addressingModes.ZeroPageZero, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.PLP, MOS6502AddressingMode.Implicit, _executor.PullProcessorStatus, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.Immediate, _executor.AndWithAccumulator, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROL, MOS6502AddressingMode.Implicit, _executor.RotateLeft, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BIT, MOS6502AddressingMode.Absolute, _executor.BitTest, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.Absolute, _executor.AndWithAccumulator, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROL, MOS6502AddressingMode.Absolute, _executor.RotateLeft, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BMI, MOS6502AddressingMode.Relative, _executor.BranchOnMinus, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.IndirectY, _executor.AndWithAccumulator, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.ZeroPageX, _executor.AndWithAccumulator, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROL, MOS6502AddressingMode.ZeroPageX, _executor.RotateLeft, _addressingModes.ZeroPageX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SEC, MOS6502AddressingMode.Implicit, _executor.SetCarry, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.AbsoluteY, _executor.AndWithAccumulator, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.AND, MOS6502AddressingMode.AbsoluteX, _executor.AndWithAccumulator, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROL, MOS6502AddressingMode.AbsoluteX, _executor.RotateLeft, _addressingModes.AbsoluteX, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.RTI, MOS6502AddressingMode.Implicit, _executor.ReturnFromInterrupt, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.IndirectX, _executor.ExclusiveOr, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.ZeroPageZero, _executor.ExclusiveOr, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LSR, MOS6502AddressingMode.ZeroPageZero, _executor.LogicalShiftRight, _addressingModes.ZeroPageZero, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.PHA, MOS6502AddressingMode.Implicit, _executor.PushAccumulator, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.Immediate, _executor.ExclusiveOr, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LSR, MOS6502AddressingMode.Implicit, _executor.LogicalShiftRight, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.JMP, MOS6502AddressingMode.Absolute, _executor.Jump, _addressingModes.Absolute, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.Absolute, _executor.ExclusiveOr, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LSR, MOS6502AddressingMode.Absolute, _executor.LogicalShiftRight, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BVC, MOS6502AddressingMode.Relative, _executor.BranchOnOverflowClear, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.IndirectY, _executor.ExclusiveOr, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.ZeroPageX, _executor.ExclusiveOr, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LSR, MOS6502AddressingMode.ZeroPageX, _executor.LogicalShiftRight, _addressingModes.ZeroPageX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CLI, MOS6502AddressingMode.Implicit, _executor.ClearInterruptDisable, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.AbsoluteY, _executor.ExclusiveOr, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.EOR, MOS6502AddressingMode.AbsoluteX, _executor.ExclusiveOr, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LSR, MOS6502AddressingMode.AbsoluteX, _executor.LogicalShiftRight, _addressingModes.AbsoluteX, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.RTS, MOS6502AddressingMode.Implicit, _executor.ReturnFromSubroutine, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.IndirectX, _executor.AddWithCarry, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.ZeroPageZero, _executor.AddWithCarry, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROR, MOS6502AddressingMode.ZeroPageZero, _executor.RotateRight, _addressingModes.ZeroPageZero, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.PLA, MOS6502AddressingMode.Implicit, _executor.PullAccumulator, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.Immediate, _executor.AddWithCarry, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROR, MOS6502AddressingMode.Implicit, _executor.RotateRight, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.JMP, MOS6502AddressingMode.Indirect, _executor.Jump, _addressingModes.Indirect, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.Absolute, _executor.AddWithCarry, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROR, MOS6502AddressingMode.Absolute, _executor.RotateRight, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BVS, MOS6502AddressingMode.Relative, _executor.BranchOnOverflowSet, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.IndirectY, _executor.AddWithCarry, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.ZeroPageX, _executor.AddWithCarry, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROR, MOS6502AddressingMode.ZeroPageX, _executor.RotateRight, _addressingModes.ZeroPageX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SEI, MOS6502AddressingMode.Implicit, _executor.SetInterruptDisable, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.AbsoluteY, _executor.AddWithCarry, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ADC, MOS6502AddressingMode.AbsoluteX, _executor.AddWithCarry, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.ROR, MOS6502AddressingMode.AbsoluteX, _executor.RotateRight, _addressingModes.AbsoluteX, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.IndirectX, _executor.StoreAccumulator, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STY, MOS6502AddressingMode.ZeroPageZero, _executor.StoreY, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.ZeroPageZero, _executor.StoreAccumulator, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STX, MOS6502AddressingMode.ZeroPageZero, _executor.StoreX, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.DEY, MOS6502AddressingMode.Implicit, _executor.DecrementY, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.TXA, MOS6502AddressingMode.Implicit, _executor.TransferXToAccumulator, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STY, MOS6502AddressingMode.Absolute, _executor.StoreY, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.Absolute, _executor.StoreAccumulator, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STX, MOS6502AddressingMode.Absolute, _executor.StoreX, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BCC, MOS6502AddressingMode.Relative, _executor.BranchOnCarryClear, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.IndirectY, _executor.StoreAccumulator, _addressingModes.IndirectY, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STY, MOS6502AddressingMode.ZeroPageX, _executor.StoreY, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.ZeroPageX, _executor.StoreAccumulator, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STX, MOS6502AddressingMode.ZeroPageY, _executor.StoreX, _addressingModes.ZeroPageY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.TYA, MOS6502AddressingMode.Implicit, _executor.TransferYToAccumulator, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.AbsoluteY, _executor.StoreAccumulator, _addressingModes.AbsoluteY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.TXS, MOS6502AddressingMode.Implicit, _executor.TransferXToStackPointer, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.STA, MOS6502AddressingMode.AbsoluteX, _executor.StoreAccumulator, _addressingModes.AbsoluteX, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDY, MOS6502AddressingMode.Immediate, _executor.LoadY, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.IndirectX, _executor.LoadAccumulator, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDX, MOS6502AddressingMode.Immediate, _executor.LoadX, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDY, MOS6502AddressingMode.ZeroPageZero, _executor.LoadY, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.ZeroPageZero, _executor.LoadAccumulator, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDX, MOS6502AddressingMode.ZeroPageZero, _executor.LoadX, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.TAY, MOS6502AddressingMode.Implicit, _executor.TransferAccumulatorToY, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.Immediate, _executor.LoadAccumulator, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.TAX, MOS6502AddressingMode.Implicit, _executor.TransferAccumulatorToX, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDY, MOS6502AddressingMode.Absolute, _executor.LoadY, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.Absolute, _executor.LoadAccumulator, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDX, MOS6502AddressingMode.Absolute, _executor.LoadX, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BCS, MOS6502AddressingMode.Relative, _executor.BranchOnCarrySet, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.IndirectY, _executor.LoadAccumulator, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDY, MOS6502AddressingMode.ZeroPageX, _executor.LoadY, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.ZeroPageX, _executor.LoadAccumulator, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDX, MOS6502AddressingMode.ZeroPageY, _executor.LoadX, _addressingModes.ZeroPageY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CLV, MOS6502AddressingMode.Implicit, _executor.ClearOverflow, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.AbsoluteY, _executor.LoadAccumulator, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.TSX, MOS6502AddressingMode.Implicit, _executor.TransferStackPointerToX, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDY, MOS6502AddressingMode.AbsoluteX, _executor.LoadY, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDA, MOS6502AddressingMode.AbsoluteX, _executor.LoadAccumulator, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.LDX, MOS6502AddressingMode.AbsoluteY, _executor.LoadX, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CPY, MOS6502AddressingMode.Immediate, _executor.CompareWithY, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.IndirectX, _executor.CompareWithAccumulator, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CPY, MOS6502AddressingMode.ZeroPageZero, _executor.CompareWithY, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.ZeroPageZero, _executor.CompareWithAccumulator, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.DEC, MOS6502AddressingMode.ZeroPageZero, _executor.Decrement, _addressingModes.ZeroPageZero, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.INY, MOS6502AddressingMode.Implicit, _executor.IncrementY, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.Immediate, _executor.CompareWithAccumulator, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.DEX, MOS6502AddressingMode.Implicit, _executor.DecrementX, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CPY, MOS6502AddressingMode.Absolute, _executor.CompareWithY, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.Absolute, _executor.CompareWithAccumulator, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.DEC, MOS6502AddressingMode.Absolute, _executor.Decrement, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BNE, MOS6502AddressingMode.Relative, _executor.BranchOnNotEqual, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.IndirectY, _executor.CompareWithAccumulator, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.ZeroPageX, _executor.CompareWithAccumulator, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.DEC, MOS6502AddressingMode.ZeroPageX, _executor.Decrement, _addressingModes.ZeroPageX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CLD, MOS6502AddressingMode.Implicit, _executor.ClearDecimal, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.AbsoluteY, _executor.CompareWithAccumulator, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.NOP, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CMP, MOS6502AddressingMode.AbsoluteX, _executor.CompareWithAccumulator, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.DEC, MOS6502AddressingMode.AbsoluteX, _executor.Decrement, _addressingModes.AbsoluteX, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CPX, MOS6502AddressingMode.Immediate, _executor.CompareWithX, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.IndirectX, _executor.SubtractWithCarry, _addressingModes.IndirectX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CPX, MOS6502AddressingMode.ZeroPageZero, _executor.CompareWithX, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.ZeroPageZero, _executor.SubtractWithCarry, _addressingModes.ZeroPageZero, 3));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.INC, MOS6502AddressingMode.ZeroPageZero, _executor.Increment, _addressingModes.ZeroPageZero, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.INX, MOS6502AddressingMode.Implicit, _executor.IncrementX, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.Immediate, _executor.SubtractWithCarry, _addressingModes.Immediate, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.NOP, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.SubtractWithCarry, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.CPX, MOS6502AddressingMode.Absolute, _executor.CompareWithX, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.Absolute, _executor.SubtractWithCarry, _addressingModes.Absolute, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.INC, MOS6502AddressingMode.Absolute, _executor.Increment, _addressingModes.Absolute, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.BEQ, MOS6502AddressingMode.Relative, _executor.BranchOnEqual, _addressingModes.Relative, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.IndirectY, _executor.SubtractWithCarry, _addressingModes.IndirectY, 5));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 8));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.ZeroPageX, _executor.SubtractWithCarry, _addressingModes.ZeroPageX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.INC, MOS6502AddressingMode.ZeroPageX, _executor.Increment, _addressingModes.ZeroPageX, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 6));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SED, MOS6502AddressingMode.Implicit, _executor.SetDecimal, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.AbsoluteY, _executor.SubtractWithCarry, _addressingModes.AbsoluteY, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.NOP, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 2));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.NoOperation, _addressingModes.Implicit, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.SBC, MOS6502AddressingMode.AbsoluteX, _executor.SubtractWithCarry, _addressingModes.AbsoluteX, 4));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.INC, MOS6502AddressingMode.AbsoluteX, _executor.Increment, _addressingModes.AbsoluteX, 7));
      _instructions.Add(new CpuInstruction(MOS6502Instruction.Invalid, MOS6502AddressingMode.Implicit, _executor.IllegalOpCode, _addressingModes.Implicit, 7));

      _logger.LogInformation("Built instructions list");
    }
  }
}
